### ISSUE TITLE
Enabling steam play for all other titles and selecting Proton flatpak makes the box uncheck after steam restart

### ISSUE THREAD

**Issue by andreldmonteiro** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#6] opened 2020-10-29 18:05 UTC
Clicking "Enable steam play for all other titles" and selecting Proton flatpak makes the box uncheck after the steam restart.

Report on steam bugtracker: https://github.com/ValveSoftware/steam-for-linux/issues/6043

**Comment by gasinvein** [comment] 2020-10-29 18:12
The checkbox gets unchecked indeed, but looks like it's still in effect - games still use Proton flatpak by default. Is it also the case for you? Click on (i) button under games banner to check which tool is selected for it.

**Comment by andreldmonteiro** [comment] 2020-10-29 18:14
Yes, it's still in effect for me.

**Comment by gasinvein** [comment] 2020-10-29 18:16
Also reproducible with Boxtron, so this might be a Steam Client bug affecting all 3rd-party compatibility tools.
@nanonyme Consider transferring this issue to Steam flatpak, until we figure out if this upstream bug or not.

**Comment by andreldmonteiro** [comment] 2020-11-09 16:26
It's fixed as in the latest steam flatpak update.

**Comment by andreldmonteiro** [comment] 2020-11-09 19:03
I'm reopening this, it's not fixed after all.

**Comment by gasinvein** [comment] 2020-11-09 19:43
Yeah, I don't think anything in recent Steam flatpak update that could affect this, or how we can affect this at all. Since it affects all 3rd-party compatibility tools, maybe it's worth reporting to the Steam Client [bugtracker](https://github.com/ValveSoftware/steam-for-linux/issues)?

**Comment by andreldmonteiro** [comment] 2020-11-09 19:51
Done: https://github.com/ValveSoftware/steam-for-linux/issues/7459

Edit: Well its a dup of https://github.com/ValveSoftware/steam-for-linux/issues/6043

Should we close this bug then?

**Comment by gasinvein** [comment] 2020-11-09 19:55
Ouch, so it's already known and reported a year ago.
>Should we close this bug then?

Yeah, we can't do anything about it from our side anyway.

**Closed as completed** 2020-11-09 19:57 UTC
Labels: wontfix
